### ISSUE TITLE
Presheaves refactoring

### ISSUE THREAD

**Issue by ramonfmir** [ramonfmir/lean-scheme#1]
The first step to getting schemes mathlib-ready is to use the language of category theory throughout the `sheaves` directory. What we need is not in the mathlib yet though, it depends on:
* [#920](https://github.com/leanprover-community/mathlib/pull/920), which is just a prerequisite for the rest.
* [#922](https://github.com/leanprover-community/mathlib/pull/922), which defines the category of open sets.
* [#886](https://github.com/leanprover-community/mathlib/pull/886), which is the definition of a presheaf on a space.

And then we will also need [#910](https://github.com/leanprover-community/mathlib/pull/910) for colimits in CommRing.

**Comment by kbuzzard** [comment]
All of these are now merged. 

https://leanprover.zulipchat.com/#narrow/stream/116395-maths/topic/gluing.20functions/near/171470883

is some Zulip chat about this issue.
