### ISSUE TITLE
adjointness of global sections map

### ISSUE THREAD

**Issue by kbuzzard** [ramonfmir/lean-scheme#3]
https://stacks.math.columbia.edu/tag/01I1

I am considering proving this -- I think it would be a neat theorem to have. I have been thinking about trying to write the paper and somehow I think it's a bit lacking in theorems. This would be a good theorem to have.

**Comment by ramonfmir** [comment]
@kckennylau proved it already! It's here: [https://github.com/ramonfmir/lean-scheme/blob/kenny/src/Kenny/sandbox.lean](https://github.com/ramonfmir/lean-scheme/blob/kenny/src/Kenny/sandbox.lean). We could try to make it work again.

**Comment by kbuzzard** [comment]
Oh fabulous! What else is proved which I don't know about?! I think that the CS people like to have theorems, but this is a pretty meaty one.

**Comment by kckennylau** [comment]
> @kckennylau proved it already! It's here: https://github.com/ramonfmir/lean-scheme/blob/kenny/src/Kenny/sandbox.lean. We could try to make it work again.

Is it not working?

**Comment by kbuzzard** [comment]
It is not (at least not with master)

**Comment by kckennylau** [comment]
Are you using mathlib version 33df7e88ddc7b9629348615ef06b2d2f8446b192?

**Comment by kbuzzard** [comment]
Oh apparently not!

**Comment by kbuzzard** [comment]
But it still doesn't compile with master :-/

**Comment by kckennylau** [comment]
well it compiles on my side so...

**Comment by kckennylau** [comment]
c.f. https://github.com/ramonfmir/lean-scheme/blob/master/src/Kenny/sandbox.lean#L523

**Comment by kckennylau** [comment]
this is the correct file in master
